### ISSUE TITLE
autohide support for paging

### ISSUE THREAD

**Issue by lapkritinis** [jhyland87/DataTables-Hide-Empty-Columns#1]
Feature request:
It would be great if autohide would have option to autohide based on what is visible on a page, not just check if column is empty for whole page:

https://datatables.net/reference/option/paging

**Comment by jhyland87** [comment]
> ...to autohide based on what is visible on a page

Not sure what you mean. Can you give an example? And whats the DT paging link for?

**Comment by lapkritinis** [comment]
paging was the feature I was referring to, therefore I have included link.
Basically if you have 100 rows with columns A, B and C. Paging is set for 20 rows.
Column C has values only in row 72-75.

So if page 0 is displayed (rows from 0 to 19) - C is hidden.
So if page 1 is displayed (rows from 20 to 39) - C is hidden.
So if page 2 is displayed (rows from 40 to 59) - C is hidden.
So if page 3 is displayed (rows from 60 to 79) - **C is shown.**
So if page 4 is displayed (rows from 80 to 99) - C is hidden.

With current plugin in all pages C column is shown event if its empty in 4 out of 5 pages.

I have sample code which does what I want, it just needs some "nice wrapping":

```
(function (window, document, $) {
    $(document).on('page.dt', function (e, dtSettings) {
        var api = new $.fn.dataTable.Api(dtSettings);
        var info = api.page.info();
        console.log(JSON.stringify(info))
        var emptyCount = 0;

        api.columns().every(function () {
            emptyCount = 0
            var data = this.data();
            for (var i = info.start; i < info.end; i++)
                if (data.toArray()[i] === null || data.toArray()[i].length === 0)
                    emptyCount++;

            if (emptyCount === (info.end - info.start)) {
                api.column(this.index()).visible(false);
            } else {
                api.column(this.index()).visible(true);
            }
        });

    });
})(window, document, jQuery);
```

**Comment by jhyland87** [comment]
This gives me an idea for another feature, something that will hide the column if its empty for the current page, and re-checks on every page change, to show populated columns and hide empty ones.

But regarding your issue, you're saying it should be shown the entire time, even if you dont see values in **that specific page**, due to the fact they **do** exist in column C, just in a **separate** page, correct?

If thats the case, It works just like that for me. I added an example of what I mean [here](http://live.datatables.net/nixohaqe/1/edit?html,js,output), you can see the column **Age** is shown, but it only has values in the 2nd page.

If thats not what you mean, can you provide an example? Feel free to copy and/or modify the example in the link I provided

**Comment by lapkritinis** [comment]
That feature what you have described - it's what I want.
I have added my code to your example [here](http://live.datatables.net/wucolupu/1/edit)
You can see it hides "Age" in first page, but unhides in second page (it triggers only on switching page - it should do it in initialization phase as well). Try switching back and forth from 1 to 2.

**Comment by jhyland87** [comment]
Ok, ill get this feature added, probably sometime this weekend.

Great idea! And thanks for using the plugin. And again, sorry for the late reply

**Comment by jhyland87** [comment]
Ive also started using ES6 a lot more... I may re-do a lot of this in ES6, and provide a transpiled version, maybe

**Comment by Lapkritinis** [comment]
I wish I knew what ES6 is :)

**Comment by jhyland87** [comment]
Haha. Newer version of JS - [Take a look](http://es6-features.org)

**Comment by jhyland87** [comment]
I added the new feature you want, its in the [hec121](https://github.com/jhyland87/DataTables-Hide-Empty-Columns/tree/hec121) branch if you wanna try it out first

**Comment by jhyland87** [comment]
http://demo.jsdigest.com/DataTables-Hide-Empty-Columns/examples/example-perpage.html Only page 3 has a value :) Try searching, ordering, etc

I just merged that into the master branch, so you can try it out. Let me know if you see any issues.

I also added a `trim` setting and a `emptyVals` setting (which you can see the emptyVals [here](http://demo.jsdigest.com/DataTables-Hide-Empty-Columns/examples/example-emptyVals.html)

**Comment by lapkritinis** [comment]
Thanks, I will definitely give it a try :)

**Comment by jhyland87** [comment]
The JS you posted was close, but I realized it wouldnt work if there was a filter in place. So I did it a little differently, [src](https://github.com/jhyland87/DataTables-Hide-Empty-Columns/blob/master/dataTables.hideEmptyColumns.js#L259-L291)

**Comment by lapkritinis** [comment]
Good job :)

**Comment by Lapkritinis** [comment]
Here is a question :) I have set [example](http://live.datatables.net/wucolupu/2/edit)
What I want to achieve:
Column "Name" should be ignored by plugin and I don't want to see it, so I hide it. Paging should not make it visible.

What I did:
If I understood correctly I have set following options:
`            hideEmptyCols: {
              columns: [0],
              whiteList: false,
              perPage: true
            }`
From documentation: whiteList "false" will target all columns except those listed

But the result is opposite - as soon as I change page - "Name" is shown again.
BUT if I set whiteList to false - it seems working as I would want?
Confused :)

**Comment by Lapkritinis** [comment]
Well I think it should be reversed logic:
Now:

`                        // If the current column is *not* found in the list..
                        if( $.inArray( this.index(), colList ) === - 1 // Check column index #
                            && $.inArray( api.column( this.index() ).dataSrc(), colList ) === - 1 )// Check column name (dataSrc)
                        {
                            // .. And the list type is whitelist, then skip this loop
                            if( isWhiteList === true ) return
                        }
                        // If the current column *is* found in the list..
                        else {
                            // .. And the list type is blacklist, then skip this loop
                            if( isWhiteList === false ) return
                        }`

Read last "else"
If the current column *is* found in the list And the list type is blacklist, then skip this loop

But documentation says: whiteList "false" will target all columns except those listed

It does reverse - it founds column and "skips loop", while it "should
