### ISSUE TITLE
Datatables stateSaving "conflicts"

### ISSUE THREAD

**Issue by lapkritinis** [jhyland87/DataTables-Hide-Empty-Columns#2]
If [stateSave](https://datatables.net/reference/option/stateSave) is enabled when page is refreshed and different data is shown in table, it doesn't unhide previously hidden columns. E.g.

There are columns A, B and C. C column is empty.

New query is performed page is refreshed and column C now longer empty, however it remains hidden.

**Comment by jhyland87** [comment]
So you're saying its the same table, but completely different data? 

Is the data different in just that one page you're on, or the entire table? Because this plugin should only hide the column if EVERY row in that column is empty (even if its on a different page), so that tells me the datatables data is completely different now (is it ajax or server side source?)

**Comment by lapkritinis** [comment]
It's same table, but data in there is different. Plugin indeed hides only empty columns, but it doesn't unhide columns which were hidden previously if page gets refreshed. I don't know what would be nice solution for this as someone might had hidden some columns "manually", otherwise I would add:

```
                if (emptyCount === data.toArray().length) {
                    api.column(this.index()).visible(false);
                } else {
                    api.column(this.index()).visible(true);
                }
```

**Comment by jhyland87** [comment]
Sorry, but im still confused. You're using the `stateSave` feature of DT, and hide a column (which will tell DT to hide it on reload), but you want HEC plugin to unhide that column? 

Im looking at the `stateSave` feature, too bad there isnt a way for you to disable it... Hm.

If in HEC, I checked if `stateSave` was enabled, and then had the logic execute **after** `stateSave` ran, would that possibly be a solution? I see stateSave has callbacks, so I should be able to inject some code into there

**Comment by lapkritinis** [comment]
Yes I am using stateSave. If HEC hides column it never gets unhidden, so dependant on the data at some point someone can get table where all data is hidden: e.g.:

Table has column A, B and C:

Query1:
Column C is empty and gets hidden. State is saved.

Query2:
Column B is now empty, C is not empty. B gets hidden, C remains hidden because of "saveState". State is saved.

Query3:
Column A is now empty, B and C are not empty. However none of columns are shown at this stage. State is saved.

[state()](https://datatables.net/reference/api/state%28%29) contains structure where its defined which columns are hidden.

As I have mentioned some user might have set column C for example hidden "on purpose".

**Comment by jhyland87** [comment]
Ok, this one will take a little more work than the other request you made, but ill definitely look into it

**Comment by jhyland87** [comment]
@Lapkritinis, im working on this now, trying to think of the best way to approach it. Do you think columns that were hidden via stateSave should be overridden on the initial page load, and set as visible? How about the opposite? 

I think maybe HideEmptyColumns should override the column visibility in the StateSave all together.

**Comment by jhyland87** [comment]
Ok, this was fixed on the last update, heres the [relevant code](https://github.com/jhyland87/DataTables-Hide-Empty-Columns/blob/master/dataTables.hideEmptyColumns.js#L296-L297), and the [code diff](https://github.com/jhyland87/DataTables-Hide-Empty-Columns/commit/ce59c2b6f286975a351729609d42668031d28b27#diff-77d92ea6ebcee2cafca116567a1e21b8R297)
