### ISSUE TITLE
columns on last page are not hidden

### ISSUE THREAD

**Issue by lapkritinis** [jhyland87/DataTables-Hide-Empty-Columns#3]
Hey, you have made same bug I had ;)

Here is [demo](http://live.datatables.net/cetivaxa/1/edit) - "Age" on last page remains unhidden because of:

`if (empty === info.length)
                            api.column(this.index()).visible(false)
                        else
                            api.column(this.index()).visible(true)`

where info.length doesn't mean that there will be same amount of rows as page could have.
Thats why I have used (info.end - info.start)

**Comment by jhyland87** [comment]
Thank you for opening this issue as well! And thanks for the demo and explanation, it definitely makes my job easier! 

Ill work on this and let you know asap.

**Comment by lapkritinis** [comment]
I already have fixes in pull requests :) been using this plugin on daily basis - no issues :)

**Comment by jhyland87** [comment]
Merged your pull request, but I guess I should have tested it a little more. This still seems to be an issue.

Reopened the ticket, and ill work on it asap

**Comment by jhyland87** [comment]
Actually, scratch that. Seems to work. I guess it was just a problem with DT Live pulling from raw github.

Thanks for contributing your work!
