### ISSUE TITLE
filter issue

### ISSUE THREAD

**Issue by lapkritinis** [jhyland87/DataTables-Hide-Empty-Columns#4]
There is another interesting issue with filtering and paging:

var data = this.data().toArray() - gets ALL columns (for example 239).

But when filtering is done, page.info is set to:
{"page":0,"pages":1,"start":0,"end":8,"length":20,"recordsTotal":239,"recordsDisplay":8,"serverSide":false}

Idea is that 
`// Only loop through the rows that are visible, using the page info
                        for (var i = info.start; i < info.end; i++) {
                            if ($.trim(data[i]) === '')
                                empty++
                        }`
loops just via FIRST 8 rows, but NOT the ones which are actually SHOWN on the screen.

**Comment by lapkritinis** [comment]
correct way to iterate would be:

```
                // Iterate through the table, column by column
                api.columns({search:'applied'}).every(function () {
```

**Comment by jhyland87** [comment]
Hello,

Thanks for using the plugin and taking the time to open an issue! And I apologize for the delayed response. 

Ill work on this and let you know when I update the repo with a fix. I'll take a look at your suggested resolution as well.

Thanks!
