### ISSUE TITLE
Access forbidden to examples URL

### ISSUE THREAD

**Issue by adriangibbons** [jhyland87/DataTables-Hide-Empty-Columns#8]
http://www.linuxdigest.org/misc/script_examples/DataTables-Hide-Empty-Columns/examples/

The above results in a **403 Forbidden** for me :'(

**Comment by adriangibbons** [comment]
For the benefit of others: if you add 'index.html' to the end of the URL it works: http://www.linuxdigest.org/misc/script_examples/DataTables-Hide-Empty-Columns/examples/index.html

**Comment by jhyland87** [comment]
This should be working now. Let me know if you have any other issues.

**Comment by adriangibbons** [comment]
Yep, works for me now. Cheers
